number1 = float(input('Введите первое число: '))
number2 = float(input('Введите второе число: '))
print('Результат сложения : %.1f' % (number1 + number2))
print('Результат вычитания : %.1f' % (number1 - number2))
print('Результат умножения : %.2f' % (number1 * number2))
print('Результат деления : %.2f' % (number1 / number2))
print('Результат возведения в степень : %.2f' % (number1 ** number2))
print('Результат деления по модулю: %.2f' % (number1 % number2))
print('Результат целочисленного деления : %.2f' % (number1 // number2))
